# Generated by Django 2.2.12 on 2020-05-20 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('siglas', models.CharField(max_length=10, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('semestre', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('siglas', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Catedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('seccion', models.CharField(choices=[('MI', 'MI'), ('MJ', 'MJ'), ('MK', 'MK'), ('ML', 'ML'), ('MM', 'MM'), ('MN', 'MN'), ('TQ', 'TQ'), ('TR', 'TR'), ('TS', 'TS'), ('TT', 'TT'), ('TU', 'TU'), ('TV', 'TV'), ('TW', 'TW'), ('NA', 'NA'), ('NB', 'NB'), ('NC', 'NC'), ('ND', 'ND'), ('NE', 'NE'), ('NF', 'NF'), ('NG', 'NG'), ('NH', 'NH')], max_length=5, null=True)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('fecha_1par', models.DateField(blank=True, null=True, verbose_name='Fecha Primer Parcial')),
                ('hora_1par', models.TimeField(blank=True, null=True, verbose_name='Hora Primer Parcial')),
                ('fecha_2par', models.DateField(blank=True, null=True, verbose_name='Fecha Segundo Parcial')),
                ('hora_2par', models.TimeField(blank=True, null=True, verbose_name='Hora Segundo Parcial')),
                ('fecha_1final', models.DateField(blank=True, null=True, verbose_name='Fecha Primer Final')),
                ('hora_1final', models.TimeField(blank=True, null=True, verbose_name='Hora Primer Final')),
                ('fecha_2final', models.DateField(blank=True, null=True, verbose_name='Fecha Segundo Final')),
                ('hora_2final', models.TimeField(blank=True, null=True, verbose_name='Hora Segundo Final')),
                ('asignaturas', models.ManyToManyField(to='academico.Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('siglas', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField(unique=True)),
                ('titulo', models.CharField(max_length=10)),
                ('titulo_grado', models.CharField(max_length=10)),
                ('posgrado', models.CharField(blank=True, max_length=10, null=True)),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('categoria_docente', models.IntegerField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoHomologas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(choices=[(1, 'Primer'), (2, 'Segundo')])),
                ('year', models.IntegerField(verbose_name='Año')),
                ('p_lec_desde', models.DateField()),
                ('p_lect_hasta', models.DateField()),
                ('par1_desde', models.DateField()),
                ('par1_hasta', models.DateField()),
                ('par2_desde', models.DateField()),
                ('par2_hasta', models.DateField()),
                ('fin1_desde', models.DateField()),
                ('fin1_hasta', models.DateField()),
                ('fin2_desde', models.DateField()),
                ('fin2_hasta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCatedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('hora_desde', models.TimeField(null=True)),
                ('hora_hasta', models.TimeField(null=True)),
                ('clase_teoria', models.BooleanField(default=False, verbose_name='Teoria')),
                ('clase_practica', models.BooleanField(default=False, verbose_name='Practica')),
                ('clase_laboratorio', models.BooleanField(default=False, verbose_name='Laborat.')),
                ('clase_taller', models.BooleanField(default=False, verbose_name='Taller')),
                ('contenidos_observacion', models.TextField(blank=True, default='', verbose_name='Observaciones del contenido')),
                ('met_exposicion', models.BooleanField(default=False, verbose_name='Exposición')),
                ('met_trabajo_ind_grp', models.BooleanField(default=False, verbose_name='Trabajo individual y/o grupal')),
                ('met_res_ejercicios', models.BooleanField(default=False, verbose_name='Resolucion de ejercicios')),
                ('met_eval', models.BooleanField(default=False, verbose_name='Evaluacion')),
                ('met_otros', models.TextField(blank=True, null=True, verbose_name='Otros metodos')),
                ('med_pizarra', models.BooleanField(default=False, verbose_name='Pizarra')),
                ('med_video', models.BooleanField(default=False, verbose_name='Video')),
                ('med_pc', models.BooleanField(default=False, verbose_name='PC - Proyector Multimedia')),
                ('med_equip', models.BooleanField(default=False, verbose_name='Equipos de Laboratorio')),
                ('med_bibli', models.BooleanField(default=False, verbose_name='Mat. Bibliograficos')),
                ('med_prog', models.BooleanField(default=False, verbose_name='Programas utilitarios')),
                ('med_otros', models.TextField(blank=True, default='', verbose_name='Especificar otros medios auxiliares')),
                ('catedra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Catedra')),
                ('contenidos_desarrollados', models.ManyToManyField(blank=True, to='academico.Contenido')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='Año')),
                ('asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Asignatura')),
            ],
            options={
                'unique_together': {('asignatura', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado')])),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('catedra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.Catedra')),
            ],
        ),
        migrations.CreateModel(
            name='Enfasis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('siglas', models.CharField(max_length=5)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.Carrera')),
            ],
        ),
        migrations.AddField(
            model_name='contenido',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.Plan'),
        ),
        migrations.AddField(
            model_name='catedra',
            name='docentes',
            field=models.ManyToManyField(to='academico.Docente'),
        ),
        migrations.AddField(
            model_name='catedra',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.Periodo'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Carrera'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Departamento'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='enfasis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.Enfasis'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='grupohomologas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.GrupoHomologas'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='prerequisito',
            field=models.ManyToManyField(blank=True, related_name='_asignatura_prerequisito_+', to='academico.Asignatura'),
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
