# Generated by Django 2.2.13 on 2020-07-12 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='semestres',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fin1_desde',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fin1_hasta',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fin2_desde',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fin2_hasta',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='par1_desde',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='par1_hasta',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='par2_desde',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='par2_hasta',
            field=models.DateField(blank=True),
        ),
    ]
