# Generated by Django 2.2.13 on 2020-07-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_auto_20200711_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
