# Generated by Django 2.2.14 on 2020-08-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_auto_20200826_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='titulo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
