# Generated by Django 2.2.13 on 2020-07-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_auto_20200711_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='fin1_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fin1_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fin2_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fin2_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='par1_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='par1_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='par2_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='par2_hasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
