# Generated by Django 2.2.14 on 2020-08-13 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_auto_20200711_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenido',
            options={'ordering': ['titulo']},
        ),
        migrations.AddField(
            model_name='grupohomologas',
            name='asignatura_primaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignatura_primaria', to='academico.Asignatura'),
        ),
        migrations.AlterField(
            model_name='registrocatedra',
            name='met_otros',
            field=models.TextField(blank=True, null=True, verbose_name='Especificar otros metodos utilizados'),
        ),
        migrations.AddConstraint(
            model_name='registrocatedra',
            constraint=models.UniqueConstraint(fields=('fecha', 'catedra', 'docente'), name='unique_registrocatedra'),
        ),
    ]
