# Generated by Django 2.2.14 on 2020-09-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_auto_20200826_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='siglas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SOL_PERMISO', 'Solicitud de Permiso'), ('MJ', 'MJ')], max_length=15)),
                ('fecha', models.DateField(blank=True)),
                ('nro_acta', models.IntegerField(blank=True)),
                ('nro_res', models.CharField(max_length=15)),
                ('URL', models.URLField(blank=True)),
                ('docentes_relacionados', models.ManyToManyField(to='academico.Docente')),
            ],
        ),
    ]
