# Generated by Django 2.2.14 on 2020-09-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_auto_20200922_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='otra_numeracion',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('ACTA_CD', 'Acta Consejo Directivo'), ('ACTA_CSU', 'Acta Consejo Superior Universitario')], max_length=15),
        ),
    ]
