# Generated by Django 2.2.14 on 2020-08-13 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_auto_20200813_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocatedra',
            name='catedra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.Catedra'),
        ),
        migrations.AlterField(
            model_name='registrocatedra',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.Docente'),
        ),
    ]
