# Generated by Django 2.2.14 on 2020-08-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_auto_20200825_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrocatedra',
            options={'permissions': [('can_list_own', 'Puede listar registros de catedra propios'), ('can_add_own', 'Puede añadir sus Registros de Catedra propios')]},
        ),
    ]
